/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as CampusRouteRouteImport } from './routes/campus/route'
import { Route as CommunityRouteRouteImport } from './routes/community/route'
import { Route as HireRouteRouteImport } from './routes/hire/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppInternshipsRouteImport } from './routes/app/internships'
import { Route as AppInterviewRouteImport } from './routes/app/interview'
import { Route as AppJobsRouteImport } from './routes/app/jobs'
import { Route as AppLearnRouteImport } from './routes/app/learn'
import { Route as AppNetworkRouteImport } from './routes/app/network'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppResumeRouteImport } from './routes/app/resume'
import { Route as AppSalaryRouteImport } from './routes/app/salary'
import { Route as AppTrackerRouteImport } from './routes/app/tracker'
import { Route as CampusIndexRouteImport } from './routes/campus/index'
import { Route as CommunityIndexRouteImport } from './routes/community/index'
import { Route as HireIndexRouteImport } from './routes/hire/index'
import { Route as HireCandidatesRouteImport } from './routes/hire/candidates'
import { Route as HireJobsRouteImport } from './routes/hire/jobs'
import { Route as HirePeopleRouteImport } from './routes/hire/people'
import { Route as HirePipelineRouteImport } from './routes/hire/pipeline'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppJobsIndexRouteImport } from './routes/app/jobs.index'
import { Route as AppJobsJobIdRouteImport } from './routes/app/jobs.$jobId'
import { Route as AppLearnIndexRouteImport } from './routes/app/learn.index'
import { Route as AppLearnCourseIdRouteImport } from './routes/app/learn.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusRouteRoute = CampusRouteRouteImport.update({
  id: '/campus',
  path: '/campus',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRouteRoute = CommunityRouteRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const HireRouteRoute = HireRouteRouteImport.update({
  id: '/hire',
  path: '/hire',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInternshipsRoute = AppInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInterviewRoute = AppInterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJobsRoute = AppJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLearnRoute = AppLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppNetworkRoute = AppNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppResumeRoute = AppResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalaryRoute = AppSalaryRouteImport.update({
  id: '/salary',
  path: '/salary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTrackerRoute = AppTrackerRouteImport.update({
  id: '/tracker',
  path: '/tracker',
  getParentRoute: () => AppRouteRoute,
} as any)
const CampusIndexRoute = CampusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CampusRouteRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRouteRoute,
} as any)
const HireIndexRoute = HireIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HireRouteRoute,
} as any)
const HireCandidatesRoute = HireCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => HireRouteRoute,
} as any)
const HireJobsRoute = HireJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => HireRouteRoute,
} as any)
const HirePeopleRoute = HirePeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => HireRouteRoute,
} as any)
const HirePipelineRoute = HirePipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => HireRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppJobsJobIdRoute = AppJobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => AppJobsRoute,
} as any)
const AppLearnIndexRoute = AppLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLearnRoute,
} as any)
const AppLearnCourseIdRoute = AppLearnCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => AppLearnRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/campus': typeof CampusRouteRouteWithChildren
  '/community': typeof CommunityRouteRouteWithChildren
  '/hire': typeof HireRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/network': typeof AppNetworkRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/tracker': typeof AppTrackerRoute
  '/hire/candidates': typeof HireCandidatesRoute
  '/hire/jobs': typeof HireJobsRoute
  '/hire/people': typeof HirePeopleRoute
  '/hire/pipeline': typeof HirePipelineRoute
  '/app/': typeof AppIndexRoute
  '/campus/': typeof CampusIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/hire/': typeof HireIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/learn/': typeof AppLearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/network': typeof AppNetworkRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/tracker': typeof AppTrackerRoute
  '/hire/candidates': typeof HireCandidatesRoute
  '/hire/jobs': typeof HireJobsRoute
  '/hire/people': typeof HirePeopleRoute
  '/hire/pipeline': typeof HirePipelineRoute
  '/app': typeof AppIndexRoute
  '/campus': typeof CampusIndexRoute
  '/community': typeof CommunityIndexRoute
  '/hire': typeof HireIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/jobs': typeof AppJobsIndexRoute
  '/app/learn': typeof AppLearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/campus': typeof CampusRouteRouteWithChildren
  '/community': typeof CommunityRouteRouteWithChildren
  '/hire': typeof HireRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/app/internships': typeof AppInternshipsRoute
  '/app/interview': typeof AppInterviewRoute
  '/app/jobs': typeof AppJobsRouteWithChildren
  '/app/learn': typeof AppLearnRouteWithChildren
  '/app/network': typeof AppNetworkRoute
  '/app/profile': typeof AppProfileRoute
  '/app/resume': typeof AppResumeRoute
  '/app/salary': typeof AppSalaryRoute
  '/app/tracker': typeof AppTrackerRoute
  '/hire/candidates': typeof HireCandidatesRoute
  '/hire/jobs': typeof HireJobsRoute
  '/hire/people': typeof HirePeopleRoute
  '/hire/pipeline': typeof HirePipelineRoute
  '/app/': typeof AppIndexRoute
  '/campus/': typeof CampusIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/hire/': typeof HireIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/jobs/$jobId': typeof AppJobsJobIdRoute
  '/app/learn/$courseId': typeof AppLearnCourseIdRoute
  '/app/jobs/': typeof AppJobsIndexRoute
  '/app/learn/': typeof AppLearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/campus'
    | '/community'
    | '/hire'
    | '/login'
    | '/app/internships'
    | '/app/interview'
    | '/app/jobs'
    | '/app/learn'
    | '/app/network'
    | '/app/profile'
    | '/app/resume'
    | '/app/salary'
    | '/app/tracker'
    | '/hire/candidates'
    | '/hire/jobs'
    | '/hire/people'
    | '/hire/pipeline'
    | '/app/'
    | '/campus/'
    | '/community/'
    | '/hire/'
    | '/api/auth/$'
    | '/app/jobs/$jobId'
    | '/app/learn/$courseId'
    | '/app/jobs/'
    | '/app/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/internships'
    | '/app/interview'
    | '/app/network'
    | '/app/profile'
    | '/app/resume'
    | '/app/salary'
    | '/app/tracker'
    | '/hire/candidates'
    | '/hire/jobs'
    | '/hire/people'
    | '/hire/pipeline'
    | '/app'
    | '/campus'
    | '/community'
    | '/hire'
    | '/api/auth/$'
    | '/app/jobs/$jobId'
    | '/app/learn/$courseId'
    | '/app/jobs'
    | '/app/learn'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/campus'
    | '/community'
    | '/hire'
    | '/login'
    | '/app/internships'
    | '/app/interview'
    | '/app/jobs'
    | '/app/learn'
    | '/app/network'
    | '/app/profile'
    | '/app/resume'
    | '/app/salary'
    | '/app/tracker'
    | '/hire/candidates'
    | '/hire/jobs'
    | '/hire/people'
    | '/hire/pipeline'
    | '/app/'
    | '/campus/'
    | '/community/'
    | '/hire/'
    | '/api/auth/$'
    | '/app/jobs/$jobId'
    | '/app/learn/$courseId'
    | '/app/jobs/'
    | '/app/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  CampusRouteRoute: typeof CampusRouteRouteWithChildren
  CommunityRouteRoute: typeof CommunityRouteRouteWithChildren
  HireRouteRoute: typeof HireRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus': {
      id: '/campus'
      path: '/campus'
      fullPath: '/campus'
      preLoaderRoute: typeof CampusRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire': {
      id: '/hire'
      path: '/hire'
      fullPath: '/hire'
      preLoaderRoute: typeof HireRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/internships': {
      id: '/app/internships'
      path: '/internships'
      fullPath: '/app/internships'
      preLoaderRoute: typeof AppInternshipsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/interview': {
      id: '/app/interview'
      path: '/interview'
      fullPath: '/app/interview'
      preLoaderRoute: typeof AppInterviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/jobs': {
      id: '/app/jobs'
      path: '/jobs'
      fullPath: '/app/jobs'
      preLoaderRoute: typeof AppJobsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/learn': {
      id: '/app/learn'
      path: '/learn'
      fullPath: '/app/learn'
      preLoaderRoute: typeof AppLearnRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/network': {
      id: '/app/network'
      path: '/network'
      fullPath: '/app/network'
      preLoaderRoute: typeof AppNetworkRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/resume': {
      id: '/app/resume'
      path: '/resume'
      fullPath: '/app/resume'
      preLoaderRoute: typeof AppResumeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/salary': {
      id: '/app/salary'
      path: '/salary'
      fullPath: '/app/salary'
      preLoaderRoute: typeof AppSalaryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tracker': {
      id: '/app/tracker'
      path: '/tracker'
      fullPath: '/app/tracker'
      preLoaderRoute: typeof AppTrackerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/campus/': {
      id: '/campus/'
      path: '/'
      fullPath: '/campus/'
      preLoaderRoute: typeof CampusIndexRouteImport
      parentRoute: typeof CampusRouteRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRouteRoute
    }
    '/hire/': {
      id: '/hire/'
      path: '/'
      fullPath: '/hire/'
      preLoaderRoute: typeof HireIndexRouteImport
      parentRoute: typeof HireRouteRoute
    }
    '/hire/candidates': {
      id: '/hire/candidates'
      path: '/candidates'
      fullPath: '/hire/candidates'
      preLoaderRoute: typeof HireCandidatesRouteImport
      parentRoute: typeof HireRouteRoute
    }
    '/hire/jobs': {
      id: '/hire/jobs'
      path: '/jobs'
      fullPath: '/hire/jobs'
      preLoaderRoute: typeof HireJobsRouteImport
      parentRoute: typeof HireRouteRoute
    }
    '/hire/people': {
      id: '/hire/people'
      path: '/people'
      fullPath: '/hire/people'
      preLoaderRoute: typeof HirePeopleRouteImport
      parentRoute: typeof HireRouteRoute
    }
    '/hire/pipeline': {
      id: '/hire/pipeline'
      path: '/pipeline'
      fullPath: '/hire/pipeline'
      preLoaderRoute: typeof HirePipelineRouteImport
      parentRoute: typeof HireRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/jobs/': {
      id: '/app/jobs/'
      path: '/'
      fullPath: '/app/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/jobs/$jobId': {
      id: '/app/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/app/jobs/$jobId'
      preLoaderRoute: typeof AppJobsJobIdRouteImport
      parentRoute: typeof AppJobsRoute
    }
    '/app/learn/': {
      id: '/app/learn/'
      path: '/'
      fullPath: '/app/learn/'
      preLoaderRoute: typeof AppLearnIndexRouteImport
      parentRoute: typeof AppLearnRoute
    }
    '/app/learn/$courseId': {
      id: '/app/learn/$courseId'
      path: '/$courseId'
      fullPath: '/app/learn/$courseId'
      preLoaderRoute: typeof AppLearnCourseIdRouteImport
      parentRoute: typeof AppLearnRoute
    }
  }
}

interface AppJobsRouteChildren {
  AppJobsJobIdRoute: typeof AppJobsJobIdRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
}

const AppJobsRouteChildren: AppJobsRouteChildren = {
  AppJobsJobIdRoute: AppJobsJobIdRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
}

const AppJobsRouteWithChildren =
  AppJobsRoute._addFileChildren(AppJobsRouteChildren)

interface AppLearnRouteChildren {
  AppLearnCourseIdRoute: typeof AppLearnCourseIdRoute
  AppLearnIndexRoute: typeof AppLearnIndexRoute
}

const AppLearnRouteChildren: AppLearnRouteChildren = {
  AppLearnCourseIdRoute: AppLearnCourseIdRoute,
  AppLearnIndexRoute: AppLearnIndexRoute,
}

const AppLearnRouteWithChildren = AppLearnRoute._addFileChildren(
  AppLearnRouteChildren,
)

interface AppRouteRouteChildren {
  AppInternshipsRoute: typeof AppInternshipsRoute
  AppInterviewRoute: typeof AppInterviewRoute
  AppJobsRoute: typeof AppJobsRouteWithChildren
  AppLearnRoute: typeof AppLearnRouteWithChildren
  AppNetworkRoute: typeof AppNetworkRoute
  AppProfileRoute: typeof AppProfileRoute
  AppResumeRoute: typeof AppResumeRoute
  AppSalaryRoute: typeof AppSalaryRoute
  AppTrackerRoute: typeof AppTrackerRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppInternshipsRoute: AppInternshipsRoute,
  AppInterviewRoute: AppInterviewRoute,
  AppJobsRoute: AppJobsRouteWithChildren,
  AppLearnRoute: AppLearnRouteWithChildren,
  AppNetworkRoute: AppNetworkRoute,
  AppProfileRoute: AppProfileRoute,
  AppResumeRoute: AppResumeRoute,
  AppSalaryRoute: AppSalaryRoute,
  AppTrackerRoute: AppTrackerRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface CampusRouteRouteChildren {
  CampusIndexRoute: typeof CampusIndexRoute
}

const CampusRouteRouteChildren: CampusRouteRouteChildren = {
  CampusIndexRoute: CampusIndexRoute,
}

const CampusRouteRouteWithChildren = CampusRouteRoute._addFileChildren(
  CampusRouteRouteChildren,
)

interface CommunityRouteRouteChildren {
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteRouteChildren: CommunityRouteRouteChildren = {
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteRouteWithChildren = CommunityRouteRoute._addFileChildren(
  CommunityRouteRouteChildren,
)

interface HireRouteRouteChildren {
  HireCandidatesRoute: typeof HireCandidatesRoute
  HireJobsRoute: typeof HireJobsRoute
  HirePeopleRoute: typeof HirePeopleRoute
  HirePipelineRoute: typeof HirePipelineRoute
  HireIndexRoute: typeof HireIndexRoute
}

const HireRouteRouteChildren: HireRouteRouteChildren = {
  HireCandidatesRoute: HireCandidatesRoute,
  HireJobsRoute: HireJobsRoute,
  HirePeopleRoute: HirePeopleRoute,
  HirePipelineRoute: HirePipelineRoute,
  HireIndexRoute: HireIndexRoute,
}

const HireRouteRouteWithChildren = HireRouteRoute._addFileChildren(
  HireRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  CampusRouteRoute: CampusRouteRouteWithChildren,
  CommunityRouteRoute: CommunityRouteRouteWithChildren,
  HireRouteRoute: HireRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
